_target_: src.backbone.automodel.AutoModelFromPreTrained
automodel_cls: AutoModelForCausalLM
pretrained_model_name_or_path: ${pretrained_model_name_or_path}
revision: null
trust_remote_code: true
keep_every_n_layers: 1
