_target_: src.backbone.automodel.AutoModelFromPreTrained
automodel_cls: AutoModel
pretrained_model_name_or_path: ${pretrained_model_name_or_path}
revision: null
trust_remote_code: true
num_layers: -1
keep_top_layers: false
reinit_model: false
attn_implementation: ${model.config.attn_backend}
