_target_: src.backbone.encoder_decoder.LLMasEncoderDecoderShareKV
pretrained_model_name_or_path: ${pretrained_model_name_or_path}
max_length: ${model.config.length}
attn_backend: ${model.config.attn_backend}
freeze_encoder: false
reinit_decoder: false
reinit_encoder: false
tie_encoder_decoder_weights: false
use_encoder_causal_mask: false
num_encoder_layers: -1
num_decoder_layers: -1
keep_top_decoder_layers: false
keep_top_encoder_layers: false
use_gradient_checkpointing: false
