#file: noinspection LongLine
# Not actually used, just serves as a placeholder to put `_target_` as first key
_target_: src.denoiser.base.Denoiser
config:
  _target_: src.denoiser.base.DenoiserConfig
  # Prevents backbone and noise from being instantiated when `hydra.utils.instantiate` is called.
  # These should be instantiated by in model init.
  _recursive_: false
  length: ???
  time_conditioned_backbone: null
  # OmegaConf resolver creates the dictionary that contains tokenizer config params
  tokenization_config: ${oc.create:${make_tokenization_config:${tokenizer}}}
  tokenizer_name: ${tokenizer.pretrained_model_name_or_path}
  attn_backend: "sdpa" # "sdpa", "flex_attention"
  train_on_context: false
