defaults:
  - base@_here_
  - _self_

_target_: src.denoiser.diffusion.D3PM
config:
  _target_: src.denoiser.diffusion.D3PMConfig
  keep_clean_bos: true
  T: 1000  # T > 0 indicates finite-time vs. continuous (e.g., MDLM), i.e., T = 0.
  diffusion_type: ???  # e.g., "absorbing" (MDLM)
